### ISSUE TITLE
Skip synthea download if exists

### ISSUE THREAD

**Issue by vperaEMC** [darwin-eu-dev/TestGenerator#9]
It looks like upon restarting the R-session that when I run TestGenerator::patientsCDM() that synthea-allergies-10k.zip gets redownloaded while that already has been done in previous R-session. Perhaps incorporate checking for existing download?

**Comment by ginberg** [comment]
hi @vperaEMC, have you set the "EUNOMIA_DATA_FOLDER" environment variable in R? If you haven't set it, it will be downloaded to a temporary directory and after a restart the data will be downloaded again
